services:
  traefik:
    image: traefik:v3.3
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=chaudharynizam10@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

  passman-be:
    image: ghcr.io/nizam-chaudhary/passman-be:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.passman-be.loadbalancer.server.port=3000"
      - "traefik.http.routers.passman-be.rule=Host(`api.passman.live`)"
      - "traefik.http.routers.passman-be.entrypoints=websecure"
      - "traefik.http.routers.passman-be.tls.certresolver=myresolver"
    env_file:
      - .env.prod
    networks:
      - web
    deploy:
      update_config:
        order: start-first

  loki:
    image: grafana/loki:latest
    container_name: loki
    expose:
      - 3100
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:10.1.5
    container_name: grafana
    expose:
      - 3000
    depends_on:
      - loki
      # - tempo
      # - prometheus
    secrets:
      - grafana_username
      - grafana_password
    environment:
      - GF_SECURITY_ADMIN_USER=/run/secrets/grafana_username
      - GF_SECURITY_ADMIN_PASSWORD=/run/secrets/grafana_password
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.passman-be.loadbalancer.server.port=3000"
      - "traefik.http.routers.passman-be.rule=Host(`observe.passman.live`)"
      - "traefik.http.routers.passman-be.entrypoints=websecure"
      - "traefik.http.routers.passman-be.tls.certresolver=myresolver"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  letsencrypt:
  grafana-data:

networks:
  web:
    external: true

secrets:
  grafana_username:
    external: true
  grafana_password:
    external: true
