services:
  passman-be:
    container_name: passman-be
    build:
      context: .
      target: production
    image: passman-be
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - LOGGER_TARGET=pino/file
    hostname: 'passman-be'

volumes:
  db-data:
