# Base stage
FROM node:22-slim
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /app
COPY pnpm-lock.yaml package.json /app/
RUN pnpm fetch
RUN pnpm install -r --offline
COPY . .
EXPOSE 3000
CMD [ "pnpm" , "run", "dev" ]
