services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=chaudharynizam10@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  passman-be:
    image: ghcr.io/nizam-chaudhary/passman-be:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.passman-be.loadbalancer.server.port=3000"
      - "traefik.http.routers.passman-be.rule=Host(`api.ec2-13-203-78-142.ap-south-1.compute.amazonaws.com`)"
      - "traefik.http.routers.passman-be.entrypoints=websecure"
      - "traefik.http.routers.passman-be.tls.certresolver=myresolver"
    env_file:
      - .env.prod
    deploy:
      update_config:
        order: start-first

volumes:
  letsencrypt:
