services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    command:
      - --providers.docker
      - --api.insecure=true
      - --providers.docker.exposedbydefault=false
      # - "--entrypoints.web.address=:80"
      # - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # - "--certificatesresolvers.myresolver.acme.email=chaudharynizam10@gmail.com"
      # - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # - "--entryPoints.websecure.address=:443"
      # - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - 80:80
      - 8080:8080
    networks:
      - web
    volumes:
      # - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  passman-be:
    image: passman-be:1.0.0
    build:
      context: .
    container_name: passman-be
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.services.passman-be.loadbalancer.server.port=3000
    #   - traefik.http.routers.passman-be.rule=Host(`api.localhost`)
    # - "traefik.http.routers.passman-be.entrypoints=websecure"
    # - "traefik.http.routers.passman-be.tls.certresolver=myresolver"
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - monitoring

networks:
  web:
    external: true
  monitoring:
    external: true
# volumes:
#   letsencrypt:
