services:
    passman-be:
        container_name: passman-be
        build:
            context: .
        image: passman-be:latest
        ports:
            - "3000:3000"
        env_file:
            - .env

    postgres:
        container_name: postgres
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
