services:
  passman-be:
    container_name: passman-be
    build:
      context: .
    image: passman-be:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - LOGGER_TARGET=pino/file
      - HOST=0.0.0.0
    hostname: "passman-be"
