name: Build and Deploy Passman to Docker Swarm

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create cache directory
        run: mkdir -p /tmp/.buildx-cache

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache # Path to cache Docker layers
          key: ${{ runner.os }}-buildx-${{ github.sha }} # Unique key for caching
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/nizam-chaudhary/passman-be:latest
            ghcr.io/nizam-chaudhary/passman-be:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-publish-docker-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}

      - name: Create .env file from secret
        run: |
          echo "${{ secrets.APP_ENV_FILE }}" > .env
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> .env

      - name: Docker stack deploy
        run: |
          ssh-keyscan -H ec2-13-203-78-142.ap-south-1.compute.amazonaws.com >> ~/.ssh/known_hosts
          docker context create passman-be --docker "host=ssh://{{ secrets.DOCKER_HOST_USERNAME }}@{{ secrets.DOCKER_HOST }}"
          docker context use passman-be
          docker stack config -c docker-stack.yml | docker stack deploy -c - passman --with-registry-auth
